[32mINFO[0m:     [07-03-2024 13:08:13] Set chroma_server_nofile to 65535
[32mINFO[0m:     [07-03-2024 13:08:14] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component System
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component SqliteDB
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component QuotaEnforcer
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component Posthog
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component LocalSegmentManager
[36mDEBUG[0m:    [07-03-2024 13:08:14] Starting component SegmentAPI
[32mINFO[0m:     [07-03-2024 13:08:14] Started server process [[36m78129[0m]
[32mINFO[0m:     [07-03-2024 13:08:14] Waiting for application startup.
[32mINFO[0m:     [07-03-2024 13:08:14] Application startup complete.
[32mINFO[0m:     [07-03-2024 13:08:14] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [07-03-2024 13:08:25] ::1:52554 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [07-03-2024 13:08:25] ::1:52560 - "GET /favicon.ico HTTP/1.1" 404
[32mINFO[0m:     [07-03-2024 13:15:32] ::1:53676 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:15:32] ::1:53676 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:15:32] ::1:53677 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:15:32] ::1:53677 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:15:32] ::1:53677 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:15:33] Backing off send_request(...) for 0.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:15:33] Backing off send_request(...) for 1.0s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:15:35] Backing off send_request(...) for 1.9s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [07-03-2024 13:15:37] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:01] ::1:53758 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:01] ::1:53758 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:01] ::1:53759 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:01] ::1:53759 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:02] Backing off send_request(...) for 0.4s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:03] Backing off send_request(...) for 1.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:04] Backing off send_request(...) for 1.9s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [07-03-2024 13:16:06] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:22] ::1:53828 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:22] ::1:53828 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:22] ::1:53833 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:22] ::1:53833 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:22] ::1:53833 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:16:22] Backing off send_request(...) for 0.5s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:23] Backing off send_request(...) for 1.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:16:24] Backing off send_request(...) for 3.7s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [07-03-2024 13:16:28] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:19:58] ::1:54329 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:19:58] ::1:54329 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:19:58] ::1:54330 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:19:58] ::1:54330 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:19:58] ::1:54330 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [07-03-2024 13:20:00] Backing off send_request(...) for 0.4s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:20:00] Backing off send_request(...) for 1.0s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [07-03-2024 13:20:02] Backing off send_request(...) for 3.8s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [07-03-2024 13:20:07] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:39:17] ::1:52269 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:39:17] ::1:52269 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:39:17] ::1:52270 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:39:17] ::1:52270 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:39:17] ::1:52270 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:39:18] Backing off send_request(...) for 1.0s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:39:19] Backing off send_request(...) for 1.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:39:21] Backing off send_request(...) for 1.1s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [08-03-2024 15:39:22] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:52:35] ::1:53875 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:52:35] ::1:53875 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:52:35] ::1:53876 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:52:35] ::1:53876 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:52:35] ::1:53876 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 15:52:37] Backing off send_request(...) for 0.0s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:52:37] Backing off send_request(...) for 0.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 15:52:37] Backing off send_request(...) for 1.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [08-03-2024 15:52:38] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:00:42] ::1:54900 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:00:42] ::1:54900 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:00:42] ::1:54901 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:00:42] ::1:54901 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:00:42] ::1:54901 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:00:43] Backing off send_request(...) for 0.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:00:44] Backing off send_request(...) for 0.8s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:00:45] Backing off send_request(...) for 3.0s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [08-03-2024 16:00:48] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55010 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55010 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [08-03-2024 16:01:28] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/add HTTP/1.1" 201
[32mINFO[0m:     [08-03-2024 16:01:28] ::1:55011 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:01:29] Backing off send_request(...) for 0.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:01:30] Backing off send_request(...) for 0.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:01:30] Backing off send_request(...) for 3.7s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [08-03-2024 16:01:34] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55098 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55098 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "GET /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/count HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [08-03-2024 16:02:00] Insert of existing embedding ID: id1
[33mWARNING[0m:  [08-03-2024 16:02:00] Add of existing embedding ID: id1
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/add HTTP/1.1" 201
[32mINFO[0m:     [08-03-2024 16:02:00] ::1:55099 - "POST /api/v1/collections/e9f2fb97-5889-42ed-806d-88eef8739462/get HTTP/1.1" 200
[32mINFO[0m:     [08-03-2024 16:02:01] Backing off send_request(...) for 0.1s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:02:01] Backing off send_request(...) for 1.5s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[32mINFO[0m:     [08-03-2024 16:02:03] Backing off send_request(...) for 3.1s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
[31mERROR[0m:    [08-03-2024 16:02:06] Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
